FROM rabbitmq:3.12-management
ENV RABBIT_PLUGIS_DIR /plugins
ADD https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download/v3.12.0/rabbitmq_delayed_message_exchange-3.12.0.ez /plugins/
