name: "ubdc-airbnb-local"

services:
  # This service produces tasks for workers to consume
  beat:
    image: "ubdc/ubdc-airbnb:latest"
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file:
      - .env
    command:
      - start-beat
    profiles:
      - all
      - core

  worker:
    # This service consumes tasks produced by beat
    image: "ubdc/ubdc-airbnb:latest"
    build:
      context: "."
      dockerfile: "Dockerfile"
    env_file:
      - .env
    command:
      - start-worker
    profiles:
      - all
      - core
  
  postgres:
    image: postgis/postgis:17-3.5
    volumes:
      - postgres_data:/var/lib/postgresql/
    env:
      POSTGRES_USER: ${DATABASE_USERNAME:?error}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:?error}
      POSTGRES_DB: ${DATABASE_NAME:?error}
    profiles:
      - all
      - support_services
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:?error}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:?error}
    profiles:
      - all
      - support_services
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: ./docker/postgis/PGDATA
      o: bind