---
version: "3.8"
x-default-volumes: &dev-volumes
  volumes:
    - "./src/dj_airbnb:/code/dj_airbnb"
    - "./docker-entrypoint.sh:/code/docker-entrypoint.sh"
    - "./requirements.txt:/code/requirements.txt"

services:
  beat:
    <<: *dev-volumes

  worker:
    environment:
      DJANGO_DEBUG: "True"
    <<: *dev-volumes
