version: "3.8"

services:
  db:
    build:
      context: ./docker/postgis
    image: airbnb_postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: airbnb
      POSTGRES_USER: postgres
    volumes:
      - db_volume:/var/lib/postgresql/data
      - "./postgis/config:/pg_config"

  rabbit:
    image: library/rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: carrot
    ports:
      - 5672:5672
      - 8080:15672

  beat:
    build:
      context: .
      dockerfile: ./docker/airbnb/Dockerfile
    image: ubdc/ubdc_beat
    volumes:
      - type: bind
        source: ./src
        target: /code
      - type: bind
        source: ./docker-entrypoint.sh
        target: /code/docker-entrypoint.sh
      - "./requirements.txt:/code/requirements.txt"
    environment:
      DJANGO_DEBUG: "False"
      MODE: "beat"
      CELERY_RABBITMQ_HOST: "rabbit"
      APP_DATABASE_HOST: "db"
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: ./docker/airbnb/Dockerfile
    image: ubdc/worker
    volumes:
      - type: bind
        source: ./src
        target: /code
      - type: bind
        source: ./docker-entrypoint.sh
        target: /code/docker-entrypoint.sh
      - "./requirements.txt:/code/requirements.txt"
    env_file:
      - .env
    environment:
      DJANGO_DEBUG: "False"
      MODE: "worker"
      CELERY_RABBITMQ_HOST: "rabbit"
      APP_DATABASE_HOST: "db"


volumes:
  db_volume:
