---
version: "3.8"

# 'db' -> service name of db service
x-dev-database-host: &X-DEV-DATABASE-HOST 172.20.67.45
x-dev-database-dbname: &X-DEV-DATABASE-DBNAME airbnb
x-dev-database-username: &X-DEV-DATABASE-USERNAME airbnb
x-dev-database-password: &X-DEV-DATABASE-PASSWORD airbnb

x-dev-rabbit-host: &X-DEV-RABBIT-HOST 130.209.67.41
x-dev-rabbit-username: &X-DEV-RABBITMQ-USERNAME rabbit
x-dev-rabbit-password: &X-DEV-RABBITMQ-PASSWORD carrot
x-dev-rabbit-vhost: &X-DEV-RABBITMQ-VHOST airbnb


x-default-volumes: &dev-volumes
  volumes:
    - "./src/dj_airbnb:/code/dj_airbnb"
    - "./docker-entrypoint.sh:/code/docker-entrypoint.sh"

services:
  beat:
    <<: *dev-volumes

  db:
    build:
      context: ./docker/postgis
    image: airbnb_postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: *X-DEV-DATABASE-DBNAME
      POSTGRES_USER: *X-DEV-DATABASE-USERNAME
      POSTGRES_PASSWORD: *X-DEV-DATABASE-PASSWORD
    volumes:
      - db_volume:/var/lib/postgresql/data

  rabbit:
    image: library/rabbitmq:3.8-management
    environment:
      RABBITMQ_DEFAULT_USER: *X-DEV-RABBITMQ-USERNAME
      RABBITMQ_DEFAULT_PASS: *X-DEV-RABBITMQ-PASSWORD
    ports:
      - 5672:5672
      - 8080:15672


  # main service definition at the docker-compose file
  worker: &dev-worker
    <<: *dev-volumes
    environment:
      RABBITMQ_USERNAME: *X-DEV-RABBITMQ-USERNAME
      RABBITMQ_PASSWORD: *X-DEV-RABBITMQ-PASSWORD
      RABBITMQ_VIRTUAL_HOST: *X-DEV-RABBITMQ-VHOST

      DATABASE_HOST: *X-DEV-DATABASE-HOST
      DATABASE_DBNAME: *X-DEV-DATABASE-DBNAME
      DATABASE_PASSWORD: *X-DEV-DATABASE-PASSWORD
      DATABASE_USERNAME: *X-DEV-DATABASE-USERNAME

      DJANGO_DEBUG: "True"

  pycharm:
    image: ${UBDC_DOCKER_REGISTRY:-}ubdc/ubdc_airbnb_engine:1.0.1
    environment:
      AIRBNB_PROXY: "http://${ZYTE_PROXY_KEY}:@proxy.crawlera.com:8011/"
      DJANGO_DEBUG: "True"
      RABBITMQ_HOST: *X-DEV-RABBIT-HOST

      DATABASE_HOST: *X-DEV-DATABASE-HOST
      DATABASE_DBNAME: *X-DEV-DATABASE-DBNAME
      DATABASE_PASSWORD: *X-DEV-DATABASE-PASSWORD
      DATABASE_USERNAME: *X-DEV-DATABASE-USERNAME

volumes:
  db_volume:
