# Generated by Django 3.2b1 on 2021-04-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_airbnbresponse__type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoishape',
            name='scan_for_new_listings',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
