# Generated by Django 3.2b1 on 2021-04-05 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ubdcgrid_datetime_listings_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ubdcgrid',
            old_name='datetime_listings_scan',
            new_name='datetime_last_listings_scan',
        ),
    ]
