# Generated by Django 3.2b1 on 2021-04-06 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_datetime_listings_scan_ubdcgrid_datetime_last_listings_scan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airbnblisting',
            old_name='comment_updated_at',
            new_name='reviews_updated_at',
        ),
    ]
