# Generated by Django 3.2b1 on 2021-04-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_rename_comment_updated_at_airbnblisting_reviews_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aoishape',
            name='collect_bookings',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
