# Generated by Django 3.2 on 2021-04-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_aoishape_collect_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnbresponse',
            name='_type',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('BQT', 'Booking Detail'), ('CAL', 'Calendar'), ('RVW', 'Review'), ('LST', 'Listing'), ('SRH', 'Search'), ('SHM', 'Search (MetaOnly)'), ('USR', 'User')], db_column='type', db_index=True, default='UNK', max_length=3, verbose_name='Response Type'),
        ),
    ]
