# Generated by Django 4.1.3 on 2022-11-10 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnblisting",
            name="geom_3857",
            field=django.contrib.gis.db.models.fields.PointField(
                help_text="Current Geom Point ('3857') of listing's location",
                null=True,
                srid=3857,
            ),
        ),
    ]
