# Generated by Django 4.2.10 on 2024-03-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_airbnbuser_ubdc_airbnbuser_d87o85f2_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnbresponse",
            name="listing_id",
            field=models.BigIntegerField(db_index=True, help_text="Airbnb ListingID", null=True),
        ),
        migrations.AlterField(
            model_name="airbnbresponse",
            name="payload",
            field=models.JSONField(default=dict, help_text="Response payload"),
        ),
        migrations.AlterField(
            model_name="ubdcgrid",
            name="tile_x",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="ubdcgrid",
            name="tile_y",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="ubdcgrid",
            name="tile_z",
            field=models.BigIntegerField(),
        ),
    ]
