# Generated by Django 4.2.10 on 2024-04-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_airbnbresponse_listing_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="airbnbuser",
            name="about",
            field=models.TextField(default="", help_text="Self description of the user"),
        ),
        migrations.AlterField(
            model_name="airbnbuser",
            name="first_name",
            field=models.TextField(default="airbnbuser", help_text="First name of the user"),
        ),
        migrations.AlterField(
            model_name="aoishape",
            name="collect_bookings",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="aoishape",
            name="name",
            field=models.TextField(default="A Collection Area", help_text="Name to display."),
        ),
    ]
