# Generated by Django 3.2b1 on 2021-03-14 15:41

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom_3857', django.contrib.gis.db.models.fields.PolygonField(srid=3857)),
                ('iso3_alpha', models.CharField(max_length=3)),
                ('name_0', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='worldshape',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['iso3_alpha'], name='dj_airbnb_w_iso3_al_eef0cc_btree'),
        ),
    ]
