# Generated by Django 3.2b1 on 2021-03-23 17:58

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubdc_airbnb', '0003_auto_20210317_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnbresponse',
            name='purpose_type',
        ),
        migrations.AddField(
            model_name='airbnbresponse',
            name='_type',
            field=models.CharField(choices=[('UNK', 'Unknown'), ('BKT', 'Booking Detail'), ('CAL', 'Calendar'), ('CMT', 'Comment'), ('LST', 'Listing'), ('QUO', 'Price Quote'), ('SRH', 'Search'), ('SHM', 'Search (MetaOnly)'), ('USR', 'User')], db_column='type', db_index=True, default='UNK', max_length=3, verbose_name='Response Type'),
        ),
        migrations.AlterField(
            model_name='aoishape',
            name='notes',
            field=models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Notes.'),
        ),
    ]
