# Generated by Django 3.2b1 on 2021-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubdc_airbnb', '0004_auto_20210323_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airbnbresponse',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='ubdcgrouptask',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterModelOptions(
            name='ubdctask',
            options={'ordering': ['datetime_submitted']},
        ),
        migrations.RemoveField(
            model_name='airbnblisting',
            name='response',
        ),
        migrations.AddField(
            model_name='airbnblisting',
            name='responses',
            field=models.ManyToManyField(to='ubdc_airbnb.AirBnBResponse'),
        ),
        migrations.DeleteModel(
            name='AirBnbListingLocations',
        ),
    ]
