# Generated by Django 3.2b1 on 2021-04-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubdc_airbnb', '0008_aoishape_scan_for_new_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubdcgrid',
            name='datetime_listings_scan',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
