# Generated by Django 3.2 on 2021-05-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubdc_airbnb', '0013_alter_airbnbresponse__type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airbnbresponse',
            name='resource_url',
        ),
        migrations.AddField(
            model_name='airbnbresponse',
            name='request_headers',
            field=models.JSONField(default=dict),
        ),
    ]
