# Generated by Django 3.2 on 2021-06-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubdc_airbnb', '0014_auto_20210511_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airbnblisting',
            name='listing_id',
            field=models.BigIntegerField(help_text='(PK) Airbnb ListingID', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='airbnbresponse',
            name='listing_id',
            field=models.BigIntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='airbnbreview',
            name='review_id',
            field=models.BigIntegerField(help_text='AirBNB Review id', unique=True),
        ),
        migrations.AlterField(
            model_name='airbnbuser',
            name='user_id',
            field=models.BigIntegerField(blank=True, help_text='Airbnb User id', unique=True),
        ),
    ]
