# Default values for the models

AIRBNBUSER_FIRST_NAME = "airbnbuser"
AIRBNBUSER_DISABLED = "airbnbuser-disabled"
AIRBNBUSER_LOCATION = ""
AIRBNBUSER_ABOUT = ""
AIOSHAPE_NAME = "A Collection Area"
AOISHAPE_COLLECT_CALENDARS = True
AOISHAPE_COLLECT_LISTING_DETAILS = True
AOISHAPE_COLLECT_BOOKINGS = False
AOISHAPE_COLLECT_REVIEWS = True
